global:
  name: consul
  image: hashicorp/consul-enterprise:1.10.3-ent
  datacenter: cluster-2
  enableConsulNamespaces: true
  gossipEncryption:
    secretName: consul-gossipencryptionkey
    secretKey: key
  federation:
    enabled: true
  tls:
    enabled: true
    httpsOnly: false
    enableAutoEncrypt: true
    verify: false
    serverAdditionalDNSSANs: ["consul-cluster-2.ric.gcp.hashidemos.io"]
    caCert:
      secretName: consul-federation
      secretKey: caCert
    caKey:
      secretName: consul-federation
      secretKey: caKey
  acls:
    manageSystemACLs: true
    replicationToken:
      secretName: consul-acl-replication-acl-token
      secretKey: token
  metrics:
    enabled: true
    enableAgentMetrics: true
server:
  enterpriseLicense:
    # The name of the Kubernetes secret that holds the enterprise license.
    # The secret must be in the same namespace that Consul is installed into.
    secretName: "consul-license"
    # The key within the Kubernetes secret that holds the enterprise license.
    secretKey: "license"
  extraVolumes:
  - type: secret
    name: consul-federation
    items:
      - key: serverConfigJSON
        path: config.json
    load: true
  extraConfig: |
    {
      "telemetry": {
        "prometheus_retention_time": "10s",
        "disable_hostname": true
      },
      "log_level": "INFO",
      "dns_config": {
        "service_ttl": {
          "*": "1s"
        },
        "node_ttl": "1s"
      },
      "audit" : {
        "enabled": true,
        "sink" : {
          "a_sink" : {
            "type"   :"file",
            "format" : "json",
            "path"   : "/consul/data/audit/log.json",
            "delivery_guarantee" : "best-effort",
            "rotate_duration" : "24h",
            "rotate_max_files" : 15,
            "rotate_bytes" : 25165824
          }
        }
      }
    }

connectInject:
  enabled: true
  metrics:
    defaultEnabled: true
    defaultEnableMerging: true

  consulNamespaces:
    mirroringK8S: true
  # centralConfig:
  #   enabled: true
  #   defaultProtocol: 'http'
  #   proxyDefaults: |
  #     {
  #       "envoy_prometheus_bind_addr": "0.0.0.0:9102",
  #       "envoy_extra_static_clusters_json": "{\"connect_timeout\": \"3.000s\", \"dns_lookup_family\": \"V4_ONLY\", \"lb_policy\": \"ROUND_ROBIN\", \"load_assignment\": { \"cluster_name\": \"zipkin\", \"endpoints\": [ { \"lb_endpoints\": [ { \"endpoint\": { \"address\": { \"socket_address\": { \"address\": \"zipkin.default\", \"port_value\": 9411, \"protocol\": \"TCP\" } } } } ] } ] }, \"name\": \"zipkin\", \"type\": \"STRICT_DNS\" }",
  #       "envoy_tracing_json":"{ \"http\": { \"config\": { \"collector_cluster\": \"zipkin\", \"collector_endpoint\": \"/api/v2/spans\"}, \"name\": \"envoy.tracers.zipkin\" }}"
  #     }

syncCatalog:
  enabled: true
  toConsul: true
  toK8S: false
  default: true
  addK8SNamespaceSuffix: false
  consulNamespaces:
    mirroringK8S: true
  aclSyncToken:
    secretName: consul-catalog-sync-acl-token
    secretKey: token

controller:
  enabled: true
ui:
  service:
    type: LoadBalancer
    annotations: |
      "external-dns.alpha.kubernetes.io/hostname": "consul-cluster-2.ric.gcp.hashidemos.io."
meshGateway:
  enabled: true
  wanAddress:
    source: Service
  service:
    type: LoadBalancer

ingressGateways:
  enabled: true
  defaults:
    service:
      type: LoadBalancer
      ports:
        - port: 443
  gateways:
    - name: dashboard-ingress-gateway
      service:
        annotations: |
          external-dns.alpha.kubernetes.io/hostname: "dashboard-cluster-2.ric.gcp.hashidemos.io"
    - name: webapp-cluster-2-ig
      service:
        annotations: |
          external-dns.alpha.kubernetes.io/hostname: "webapp-cluster-2.ric.gcp.hashidemos.io"

terminatingGateways:
  enabled: false
