apiVersion: v1
kind: ServiceAccount
metadata:
  name: jaeger
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zipkin
  labels:
    app: jaeger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaeger
  template:
    metadata:
      labels:
        app: jaeger
    spec:
      containers:
      - name: jaeger
        image: jaegertracing/all-in-one:1.21
        imagePullPolicy: IfNotPresent
        env:
          - name: "COLLECTOR_ZIPKIN_HTTP_PORT"
            value: "9411"
        ports:
        - containerPort: 5775
          protocol: UDP
        - containerPort: 6831
          protocol: UDP
        - containerPort: 6832
          protocol: UDP
        - containerPort: 5778
          protocol: TCP
        - containerPort: 16686
          protocol: TCP
        - containerPort: 14268
          protocol: TCP
        - containerPort: 9411
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: zipkin
  labels:
    app: jaeger
spec:
  ports:
  - port: 9411
    protocol: TCP
    targetPort: 9411
  selector:
    app: jaeger
  type: LoadBalancer

---
apiVersion: v1
kind: Service
metadata:
  annotations:
    consul.hashicorp.com/service-sync: "true"
    external-dns.alpha.kubernetes.io/hostname: jaeger-2.hc-7b910e3ece0c4fa386d0665927c.gcp.sbx.hashicorpdemo.com
  name: jaeger
  labels:
    app: jaeger
spec:
  ports:
  - port: 16686
    protocol: TCP
    targetPort: 16686
  selector:
    app: jaeger
  type: LoadBalancer