---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-v2
  namespace: webapp
  labels:
    app: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9102"
        consul.hashicorp.com/enable-metrics-merging: "false"
        consul.hashicorp.com/connect-inject: "true"
        consul.hashicorp.com/connect-service: "webapp"
        consul.hashicorp.com/connect-service-port: "5000"
        # consul.hashicorp.com/connect-service-upstreams: "local-counter.default:9001:cluster-2"
        # consul.hashicorp.com/connect-service-upstreams: "local-counter.default:9001"
        # consul.hashicorp.com/connect-service-upstreams: "external-counting.default:9001:cluster-1"
        consul.hashicorp.com/service-tags: "v2"
        consul.hashicorp.com/service-meta-version: "v2"
      labels:
        app: webapp
    spec:
      serviceAccountName: webapp
      containers:
      - name: webapp
        image: ghcr.io/gitrgoliveira/minikube-consul/webapp:v2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
          name: http
        env:
        - name: COUNTING_SERVICE_URL
          value: "http://local-counter.virtual.consul:9001"
        - name: BG_COLOR
          value: "PALEGREEN"

---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceDefaults
metadata:
  name: webapp
  namespace: webapp
spec:
  protocol: http
  transparentProxy:
    dialedDirectly: false

---

apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceResolver
metadata:
  name: webapp
  namespace: webapp
spec:
  defaultSubset: v1
  subsets:
    v1:
      filter: 'Service.Meta.version == v1'
    v2:
      filter: 'Service.Meta.version == v2'

---

apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceRouter
metadata:
  name: webapp
  namespace: webapp
spec:
  routes:
    - match:
        http:
          queryParam:
            - name: x-debug
              present: true
      destination:
        service: webapp
        serviceSubset: v2
  # NOTE: a default catch-all will send unmatched traffic to "web"

---

apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceSplitter
metadata:
  name: webapp
  namespace: webapp
spec:
  splits:
    - weight: 100
      service: webapp
      namespace: webapp
      serviceSubset: v1
    - weight: 0
      service: webapp
      namespace: webapp
      serviceSubset: v2
