apiVersion: v1
kind: Namespace
metadata:
  name: webapp
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    consul.hashicorp.com/service-sync: 'false'
  name: webapp
  namespace: webapp
  labels:
    app: webapp
spec:
  ports:
  - protocol: TCP
    port: 5000
  selector:
    app: webapp
  type: LoadBalancer
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: webapp
  namespace: webapp
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: webapp-role
  namespace: webapp
rules:
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - get
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: webapp
  namespace: webapp
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: webapp-role
subjects:
- kind: ServiceAccount
  name: webapp
  namespace: webapp

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  namespace: webapp
  labels:
    app: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9102"
        consul.hashicorp.com/enable-metrics-merging: "false"
        consul.hashicorp.com/connect-inject: "true"
        consul.hashicorp.com/transparent-proxy: "true"
        consul.hashicorp.com/connect-service: "webapp"
        consul.hashicorp.com/connect-service-port: "5000"
        # consul.hashicorp.com/connect-service-upstreams: "local-counter.default:9001:cluster-2"
        # consul.hashicorp.com/connect-service-upstreams: "local-counter.default:9001"
        # consul.hashicorp.com/connect-service-upstreams: "external-counting.default:9001:cluster-1"
        consul.hashicorp.com/service-tags: "v1"
        consul.hashicorp.com/service-meta-version: "v1"
      labels:
        app: webapp
    spec:
      serviceAccountName: webapp
      containers:
      - name: webapp
        image: ghcr.io/gitrgoliveira/minikube-consul/webapp:v2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
          name: http
        env:
        - name: COUNTING_SERVICE_URL
          value: "http://local-counter.virtual.consul:9001"
        - name: BG_COLOR
          value: "WHITE"


---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceDefaults
metadata:
  name: webapp
  namespace: webapp
spec:
  protocol: http
  transparentProxy:
    dialedDirectly: false

---

apiVersion: consul.hashicorp.com/v1alpha1
kind: IngressGateway
metadata:
  name: webapp-cluster-1-ig
spec:
  tls:
    enabled: true
  listeners:
    - port: 8443
      protocol: http
      services:
        - name: webapp
          namespace: webapp
          hosts: ['webapp-cluster-1.hc-7b910e3ece0c4fa386d0665927c.gcp.sbx.hashicorpdemo.com']

---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: webapp-ingress
spec:
  destination:
    name: webapp
    namespace: webapp
  sources:
    - name: webapp-cluster-1-ig
      namespace: default
      permissions:
        - action: allow
          http:
            pathPrefix: '/'
      