apiVersion: v1
kind: ServiceAccount
metadata:
  name: local-counter
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: local-counter
  labels:
    app: local-counter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: local-counter
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9102"
        consul.hashicorp.com/enable-metrics-merging: "false"
        consul.hashicorp.com/connect-inject: "true"
        consul.hashicorp.com/transparent-proxy: "true"
        consul.hashicorp.com/connect-service: "local-counter"
        # consul.hashicorp.com/connect-service-protocol: "tcp"
        consul.hashicorp.com/connect-service-port: "9001"
      labels:
        app: local-counter
    spec:
      serviceAccountName: local-counter
      containers:
      - name: local-counter
        image: hashicorp/counting-service:0.0.2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9001
          name: http
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    consul.hashicorp.com/service-sync: 'false'
  name: local-counter
  labels:
    app: local-counter
spec:
  ports:
  - protocol: TCP
    port: 9001
  selector:
    app: local-counter
  type: ClusterIP
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceDefaults
metadata:
  name: local-counter
  namespace: default
spec:
  protocol: 'http'
  transparentProxy:
    dialedDirectly: true
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: local-counter
spec:
  destination:
    name: local-counter
    namespace: default
  sources:
    - name: webapp
      namespace: webapp
      permissions:
        - action: allow
          http:
            pathPrefix: '/'
    - name: dashboard-service
      namespace: dashboard-service
      action: allow